aws_region: "ap-southeast-2"
aws_account_id: "125992594465"
novacart_env: "dev"
novacart_bucket: "novacart-order-analytics-125992594465-ap-southeast-2"
glue_database: "novacart"
glue_role_name: "NovaCartGlueRole"
glue_runtime: "Glue 4.0"
glue_job_name: "novacart-iceberg-smoke-test"
athena_output_location: "s3://novacart-order-analytics-125992594465-ap-southeast-2/athena-query-results/"
iceberg_warehouse: "s3://novacart-order-analytics-125992594465-ap-southeast-2/iceberg-warehouse/"
